name: Encuestame Social Survey Tool
markdown: redcarpet
highlighter: true

languages: ["en", "en", "es", "de"]

sass:
    sass_dir: _sass
    style: compressed


# Server
#destination:      _gh_pages
#host:             0.0.0.0
#port:             9001
#baseurl:          /
url:              http://www.encuestame.org
#encoding:         UTF-8

exclude:
  - sass
  - config.rb
  - Gemfile

# Custom vars
current_version:  1.5.4
in_progress    :  1.6.0-alpha
repo:             https://github.com/encuestame
project_name:     Encuestame
download:
  source:         https://sourceforge.net/projects/encuestame/files/1.5.4/
  dist:           https://sourceforge.net/projects/encuestame/files/latest/download

site_domain_url:      http://www.encuestame.org
blog:             http://encuestame.org/wiki/pages/viewrecentblogposts.action?key=~juanpicado
wiki:             http://www.encuestame.org/wiki
feedback:         https://encuestame.uservoice.com
demo:             http://www.encuestame.org/demo
issues:           http://www.encuestame.org/issues
code:             https://github.com/encuestame/encuestame/
commit:           http://encuestame.org/wiki/display/DEVELOPMENT/Commiters+Guidelines
maillist:         https://groups.google.com/forum/?hl=es#!forum/encuestame
google_groups:    https://groups.google.com/forum/?hl=es#!forum/encuestame
build:            http://www.encuestame.org/build
releases:         http://www.encuestame.org/issues/browse/ENCUESTAME/?selectedTab=com.atlassian.jira.jira-projects-plugin:versions-panel
jota_twitter:     http://www.twitter.com/jotadeveloper
dianmora_twitter:      http://www.twitter.com/dianmora
youtube_channel:   http://www.youtube.com/channel/UCXCTTWRQXfArc_8J7O2P6Yg
license_url:       https://raw.github.com/encuestame/encuestame/master/LICENSE.txt
license_site:     https://creativecommons.org/licenses/by/3.0/

getting:
   web1: http://encuestame.org/wiki/display/DOC/How+to+build+Encuestame
   web2: http://encuestame.org/wiki/display/DOC/Download
   wizard1: http://encuestame.org/wiki/display/DOC/Encuestame+Installation+Guide
   wizard2: http://encuestame.org/wiki/display/DOC/Wizard+Installation
   how1: http://encuestame.org/wiki/display/DOC/Encuestame+Documentation
   how2: http://encuestame.org/wiki/display/DOC/Encuestame+Documentation
   how3: http://encuestame.org/wiki/display/DOC/Encuestame+Documentation
   how4: http://encuestame.org/wiki/display/DOC/Encuestame+Documentation

contri:
    juanpicado_github: https://github.com/juanpicado
    dianmorales_github: https://github.com/dianmorales
